export type ValidSkills =
  | "AWS" 
  | "Angular" 
  | "CSS 3" 
  | "Databricks" 
  | "GraphQL" 
  | "HTML 5" 
  | "IT人材市場" 
  | "Java" 
  | "Javascript"
  | "KPI設計" 
  | "MongoDB" 
  | "Next.js" 
  | "Node.js" 
  | "PMO" 
  | "Python" 
  | "React" 
  | "Typescript" 
  | "アジャイル開発"
  | "アライアンス" 
  | "イベント運営" 
  | "エンジェル投資" 
  | "スタートアップ" 
  | "スタートアップ経営" 
  | "ダッシュボード構築"
  | "デジタルマーケティング" 
  | "プロジェクトマネジメント" 
  | "マッチングシステム" 
  | "メディア運営" 
  | "リモート開発体制"
  | "事業開発" 
  | "人事管理" 
  | "人材サービス" 
  | "危機管理" 
  | "営業企画" 
  | "営業戦略" 
  | "採用" 
  | "教育開発"
  | "数値管理"
  | "新規事業立ち上げ" 
  | "業務改善"
  | "法務対応" 
  | "組織マネジメント" 
  | "経営アドバイザー"
  | "経営企画" 
  | "財務会計" 
  | "資金調達" 
  | "農業ビジネス" 
  | "関係人口創出";
  
export type ValidCategory =
  | "Full Stack"
  | "Frontend"
  | "Backend"
  | "UI/UX"
  | "Web Dev"
  | "Mobile Dev"
  | "3D Modeling";

export type ValidExpType = "Personal Project" | "Professional";

export type ValidPages =
  | "home"
  | "skills"
  | "experience"
  | "career"
  | "contact"
  | "contributions"
  | "resume";
